name = "config-editor"
compatibility_date = "2025-05-15"
pages_build_output_dir = "./dist"

[[r2_buckets]]
binding = "CONFIG_BUCKET"
bucket_name = "config-editor-bucket"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "d42118a5f27740f1af412a0facea7250"